export const civicAndNews: string[] = [
  "council packet revised after copier jam",
  "trash route B observes the old Tuesday",
  "library basement cooling center hours TBD",
  "notice of benches awaiting public comment",
  "mayor thanks everyone for the cones",
  "school closed due to boiler optimism",
  "zoning map shows a future rectangle",
  "agenda item 7b: decorative storm drains",
  "local paper corrects spelling of culvert",
  "public hearing moved to room with clock",
  "directory lists acting deputy mailbox lead",
  "snow emergency declared for sunny blocks",
  "water advisory lifted for one hydrant",
  "committee studies shade near the mailbox",
  "stale headline: parade still anticipated",
  "civic center door three remains mysterious",
  "permit desk now accepts blue forms",
  "school buses delayed by ceremonial geese",
  "board minutes mention unresolved humming",
  "council update: banners are mostly legal",
  "policy panel weighs curbside sincerity",
  "notice: fountain testing may look official",
  "local news: pothole receives temporary name",
  "directory: senior coordinator of plaques",
  "recreation signup paused during stapler audit",
  "town hall livestream has excellent ceiling",
  "unclaimed bikes sorted by general mood",
  "planning commission rejects invisible kiosk",
  "winter parking begins when signs remember",
  "school closure notice printed sideways",
  "park district seeks opinions on mulch tone",
  "council packet includes four blank apologies",
  "public notice taped over earlier public notice",
  "town newsletter praises durable sandwich board",
  "election office tests envelopes with gravity",
  "health board reviews suspiciously warm yogurt",
  "storm report filed under miscellaneous drizzle",
  "directory says call Janet, probably",
  "headline: old mill still nearly redeveloped",
  "agenda amended to include missing amendment",
  "parking meters enter brief listening period",
  "school lunch menu cites pending casserole",
  "council chamber carpet receives variance",
  "public works confirms salt pile silhouette",
  "local paper asks who moved the clock",
  "policy panel agrees to define kiosk",
  "library notice: microfilm machine has opinions",
  "city clerk posts minutes in reverse confidence",
  "water tower mural delayed by clouds",
  "transit update: route 12 honors detour",
  "school closed for districtwide key confusion",
  "directory updated except for all extensions",
  "public notice: siren test was not siren test",
  "council update praises competitive leaf piles",
  "headline from March: bridge study continues",
  "permit window open beside closed window",
  "parks memo discusses benches facing choices",
  "zoning appeal cites historic shrub line",
  "local news briefs include heroic clipboard",
  "policy panel convenes over sidewalk feelings",
  "school closure due to cafeteria fog",
  "public notice folded into impossible thirds",
  "council votes to rename unnamed lane later",
  "directory lists dog license fax tradition",
  "road work begins after final pre-beginning",
  "stale headline: budget retreat still pending",
  "rec center posts rules for imaginary pickleball",
  "municipal page loads photo of empty lectern",
  "agenda notes typo in previous typo correction",
  "public comment limited to microphone distance",
  "school board praises emergency glitter plan",
  "local paper maps the wrong roundabout",
  "policy panel studies forms about forms",
  "council update: flagpole rope situation stable",
  "notice of temporary permanent barricade",
  "directory: assistant to interim bulletin person",
  "trash calendar omits the eighth Wednesday",
  "school closed while roof makes decisions",
  "town website welcomes residents to 2021",
  "public hearing postponed for chair shortage",
  "headline: diner sign may become landmark",
  "council packet appendix has appendix energy",
  "planning map labels creek as possible rumor",
  "health notice asks casseroles to self-report",
  "library board debates whisper enforcement",
  "policy panel releases draft of draft cover",
  "street sweeping delayed by parade paperwork",
  "directory says office hours vary by bell",
  "school closure alert sent after reopening",
  "public works measures suspicious curb enthusiasm",
  "local news: committee applauds revised cones",
  "city council thanks the subcommittee twice",
  "notice: pool rules apply to dry pool",
  "budget dashboard stuck on encouraging beige",
  "zoning page shows parcel with no destiny",
  "headline: county fair seeks quieter ribbon",
  "transit detour detoured around detour notice",
  "school district updates snow day philosophy",
  "municipal archive stores newsletter named final2",
  "policy panel asks residents to rank waiting",
  "public notice expires before bulletin opens",
  "council update: mural concept is less rectangle",
  "directory lists parks voicemail as seasonal",
  "storm shelter sign points at printer room",
  "local headline: gazebo report enters phase zero",
  "school closed for unexplained hallway moisture",
  "committee minutes approve minutes about minutes",
  "city page apologizes for celebratory outage",
  "public notice: alley cats are not agenda",
  "policy panel adjourns pending better acronym",
  "council packet footnote references lost binder"
];
