export const commerceAndMarkets: string[] = [
  "cart smells like fresh copper",
  "only three left in the bin",
  "subscription renews under the floorboards",
  "checkout button blinks twice",
  "free shipping after midnight",
  "merchant notes written in pencil",
  "bundle the velvet cables",
  "price drops when nobody watches",
  "wishlist full of spare moons",
  "coupon code: TINY-STORM",
  "inventory says maybe",
  "seller badge still warm",
  "abandoned cart hums softly",
  "promo banner ate the margin",
  "product grid with one missing tooth",
  "marketplace stall number zero",
  "backorder with a candle icon",
  "returns desk beneath the stairs",
  "loyalty points in a jar",
  "featured deal looks nervous",
  "add to cart, hear a bell",
  "one-click purchase, no eye contact",
  "shipping label printed sideways",
  "the upsell knows your shoe size",
  "flash sale in the greenhouse",
  "seller rating: mostly fog",
  "warehouse aisle marked etc",
  "gift card balance: one whisper",
  "invoice folded into quarters",
  "product photo taken by moonlight",
  "low-stock warning with teeth",
  "tax estimate keeps changing names",
  "checkout progress bar limps",
  "cart drawer sticks at dusk",
  "recommended because you hovered",
  "subscription tier: attic gold",
  "compare at price is blushing",
  "inventory sync missed lunch",
  "retail ops clipboard of omens",
  "promo page above the laundromat",
  "market fee under the rug",
  "variant picker chooses itself",
  "size chart from another climate",
  "delivery window: before rain",
  "saved payment card is haunted",
  "order confirmation in lowercase",
  "cart recovery email, subject: hey",
  "merchant payout arrives in coins",
  "discount stack wobbles badly",
  "product title too honest",
  "checkout modal forgot its hat",
  "subscription pause button sighs",
  "retail queue bends left",
  "price tag tied with blue thread",
  "clearance rack has opinions",
  "customer segment: night owls",
  "SKU written on a lemon",
  "product feed sneezes duplicates",
  "marketplace search finds a ladder",
  "same-day delivery by mysterious van",
  "bundle builder needs tea",
  "cart total includes tiny thunder",
  "campaign landing page smells minty",
  "order note: leave by the cactus",
  "promo timer counts in crumbs",
  "vendor portal opens reluctantly",
  "receipt printer speaks in dots",
  "fulfillment bin full of echoes",
  "cross-sell the brass spoon",
  "sale badge stuck to the ceiling",
  "checkout field asks for courage",
  "warehouse scan says nope",
  "wishlist reminder with a wink",
  "subscription upgrade glows faintly",
  "product filters sorted by rumor",
  "bulk order from the basement",
  "coupon expired but still smiling",
  "pickup shelf labeled soon",
  "cart subtotal before prophecy",
  "merchant dashboard has a pulse",
  "promo code hidden in the footer",
  "stock count: twelve and a half",
  "shipping zone beyond the map",
  "retail calendar skips Tuesday",
  "product badge: oddly fresh",
  "checkout iframe breathes slowly",
  "abandoned basket of chrome pears",
  "pricing table with soft corners",
  "market stall accepts cloud money",
  "return label smells like ink",
  "subscription churn prediction yawns",
  "cart page under construction tape",
  "best seller in cabinet shadows",
  "payment failed, try softer",
  "promo hero holding a stapler",
  "order lookup by secret knock",
  "inventory audit at blue hour",
  "marketplace dispute over buttons",
  "loyalty tier: tin crown",
  "checkout breadcrumb in the sugar",
];
