export const domesticAndLifestyle: string[] = [
  "wipe the counter before the moon cools",
  "three ladles of soup and one apology",
  "linen shelf arranged by weather memory",
  "the starter hears the refrigerator hum",
  "policy footer in a soft gray voice",
  "fold towels with the label facing Tuesday",
  "add cinnamon until the room stops arguing",
  "a walnut chair for narrow breakfast thoughts",
  "your cart contains one calmer morning",
  "rinse beans while reading the warranty",
  "sleep hygiene for people with loud ceilings",
  "the pantry accepts only honest jars",
  "annual rug rotation and other small ceremonies",
  "mix until glossy but not convinced",
  "oak nightstand with secret cable weather",
  "subscribe for seasonal sink advice",
  "the bath mat has chosen boundaries",
  "hand wash cold, forgive slowly",
  "broth for rainy errands and minor grief",
  "a modular sofa with diplomatic cushions",
  "wellness begins under the loose stair",
  "terms apply to all scented candles",
  "hang herbs where the gossip can dry",
  "five minute reset for cabinet doubt",
  "the casserole travels under foil armor",
  "basket set for lemons, socks, and receipts",
  "make the bed like an alibi",
  "gentle cleanser for marble and moods",
  "a guide to hosting quiet relatives",
  "knead until the dough remembers summer",
  "floor lamp with a patient brass neck",
  "privacy choices beside the gravy recipe",
  "steam greens until vividly obedient",
  "organize drawers by future excuses",
  "the porch swing prefers unsent letters",
  "daily tonic with optional skepticism",
  "free shipping after the fourth impulse",
  "measure rice with the emergency mug",
  "a washable slipcover for dramatic pets",
  "morning pages between compost and coffee",
  "simmer onions past the first regret",
  "glassware for water, guests, and omens",
  "cleanse the entryway of old umbrellas",
  "curated essentials for the laundry plateau",
  "the newsletter smells faintly of nutmeg",
  "bench cushion in improbable coastal blue",
  "stir clockwise for archival reasons",
  "your consent may be managed below",
  "a tiny spoon for ceremonial mustard",
  "kitchen island seeking seasonal purpose",
  "reset your nervous system near the toaster",
  "velvet ottoman with mild leadership skills",
  "leftover pie under community guidelines",
  "vacuum lines as temporary architecture",
  "add broth until the story loosens",
  "the duvet waits for better data",
  "family calendar with lunar exceptions",
  "ceramic bowl for pears and house keys",
  "terms updated during a thunderstorm",
  "a pantry audit for emotional flour",
  "snack board for uncertain visitors",
  "avoid boiling after the basil arrives",
  "the reading nook faces no court",
  "bamboo tray for tea and small denials",
  "seven stretches beside the recycling bin",
  "the placemats are machine washable rumors",
  "choose a neutral that forgives soup",
  "default cookie settings remain crisp",
  "fluff pillows until morale improves",
  "toast walnuts in a vigilant pan",
  "the armoire contains weekend versions",
  "welcome mat with limited liability",
  "gentle habits for people with many mugs",
  "a candle labeled quiet inventory",
  "peel carrots during the long hold music",
  "catalog price excludes attic emotions",
  "the dining table seats six theories",
  "breathe in, locate the spare batteries",
  "shelf styling for introverted ceramics",
  "affiliate links may contain breakfast",
  "chill dough beneath a clean towel",
  "a bedroom set for parallel dreams",
  "mop from the corner of least resistance",
  "the soup freezes well in future tense",
  "soft robes for post-shower negotiations",
  "unsubscribe beside the lemon tart",
  "label cords before they form opinions",
  "a care guide for anxious houseplants",
  "brown butter until it smells like evidence",
  "ottoman storage for games and grievances",
  "the capsule wardrobe includes a rain spoon",
  "privacy notice revised after brunch",
  "sweep crumbs toward a better quarter",
  "do not microwave the heirloom bowl",
  "wellness kit with tea, tape, and permission",
  "the sideboard glows under practical lamps",
  "season to taste, then leave town",
  "linen curtains for filtered admissions",
  "a fifteen step guide to simpler drawers",
  "cookie banner with a pie crust edge",
  "let the stew rest before explanations",
  "entry hooks for coats and alternate selves",
  "the bathroom shelf has a quiet taxonomy",
  "handbook for surviving discount throws",
  "mix greens with the cautious vinaigrette",
  "a recliner that understands policy footnotes",
  "weekend reset featuring dust and peaches",
  "dishwasher safe except during eclipses",
  "your guide to mindful pantry shadows",
  "woven baskets for blankets and intentions",
  "rest the roast under a foil tent",
  "the footer remembers every coupon code",
];
