export const educationAndCourses: string[] = [
  "quiz timer coughs politely",
  "worksheet margin hides bonus algebra",
  "gradebook averages the moon",
  "campus notice pinned to thunder",
  "library card remembers every overdue leaf",
  "course module locked by vibes",
  "class forum debates the syllabus comma",
  "certificate printed before attendance",
  "LMS tab smells like pencil dust",
  "tutorial site explains the obvious sideways",
  "rubric asks for three small miracles",
  "student portal forgets homeroom",
  "attendance button marked spiritually present",
  "homework upload waits in the hallway",
  "lecture replay buffers on wisdom",
  "flashcard deck loses the back side",
  "parent login blinks in cursive",
  "grade appeal filed under weather",
  "campus map labels the quiet stairs",
  "lab worksheet requires one brave magnet",
  "discussion post cites a sandwich",
  "online seminar starts at almost noon",
  "course catalog lists advanced recess",
  "unit test graded by a lantern",
  "library checkout stamped with static",
  "diploma preview missing a Tuesday",
  "teacher dashboard hums in chalk",
  "quiz question has stage directions",
  "class roster includes temporary wizard",
  "lesson plan loops through crayons",
  "assignment draft smells like erasers",
  "campus alert mentions suspicious fog",
  "student ID photo pending thunder",
  "practice test predicts breakfast",
  "lecture notes folded into pixels",
  "certificate badge asks for glue",
  "grade cell turns into a sigh",
  "office hours moved behind login",
  "reading list annotated by dust",
  "course progress bar takes attendance",
  "peer review praises the margins",
  "library kiosk dreams of stamps",
  "school portal opens to lost mittens",
  "syllabus update arrives wearing boots",
  "exam proctor approves the wallpaper",
  "math worksheet contains polite thunder",
  "tutorial step skips to folklore",
  "class forum thread grows antlers",
  "campus notice board leaks confetti",
  "quiz retake locked until soup",
  "lesson video waves from buffering",
  "grade curve bends around Wednesday",
  "library fine paid in bookmarks",
  "certificate name set to lowercase hero",
  "student dashboard counts invisible credits",
  "course tile shivers at prerequisites",
  "worksheet answer key tells jokes",
  "LMS sidebar hides the final",
  "class announcement written by bell schedule",
  "tutorial popup asks for a compass",
  "grade report mailed to the basement",
  "campus shuttle notice rhymes badly",
  "reading quiz suspects everyone",
  "student portal password expires at lunch",
  "library card barcode hums softly",
  "course forum moderator is a rubric",
  "attendance sheet folds itself alphabetically",
  "certificate frame includes tiny homework",
  "school calendar adds pretend Friday",
  "lecture slide stuck on a fern",
  "quiz bank labels one answer probably",
  "worksheet packet stapled to rain",
  "class poll elects the projector",
  "gradebook comment says see lighthouse",
  "campus bulletin warns of extra commas",
  "tutorial page refreshes into Latin",
  "course completion sparkles suspiciously",
  "library renewal denied by moonlight",
  "student portal avatar wears mortarboard",
  "assignment rubric has a secret drawer",
  "lab safety quiz trusts no beaker",
  "forum reply posted from detention",
  "certificate download brings extra margins",
  "online course intro forgets chapter one",
  "school notice smells like wet backpacks",
  "grade histogram slopes toward snack",
  "worksheet footer asks for patience",
  "library hold queue forms a spiral",
  "campus dining alert cites poetry",
  "lesson checkpoint guarded by dropdown",
  "student transcript includes dramatic pause",
  "quiz feedback praises the pencil",
  "classroom portal serves stale badges",
  "tutorial index points at itself",
  "course prerequisite whispers maybe",
  "teacher comment needs a bookmark",
  "library printer prints quiet maps",
  "campus notice expires before sunrise",
  "worksheet problem seven has elbows",
  "certificate verification sends postcards",
  "discussion board bans all caps after dusk",
  "grade export arrives wearing tabs",
  "course video captions invent a dean",
  "school portal menu says almost there",
  "quiz hint opens a smaller quiz",
  "library card selfie rejected by shelf",
  "campus parking alert blames geometry",
  "lesson module named after static",
  "student badge unlocks the wrong hall",
  "worksheet scanner loves blue ink",
  "class forum pin points north",
  "certificate seal approved by stapler",
  "grade notification knocks twice",
  "tutorial breadcrumb enters study hall",
  "course survey asks about clouds",
  "library catalog misfiles ambition",
  "campus email subject lost its shoes",
  "quiz score rounded toward mystery",
  "school transcript whispers extracurricular fog",
  "lesson plan imports one quiet bell",
  "class resource link opens a locker",
];
