export const financeAndCrypto: string[] = [
  "balance widget blinks at noon",
  "ticker tape lost its shoes",
  "wallet sync smells like pennies",
  "invoice total looks surprised",
  "ledger row marked almost",
  "price alert under the couch",
  "bank feed arrived sideways",
  "portfolio chart has hiccups",
  "crypto candle burns green",
  "budget app wants a snack",
  "routing number in pencil",
  "market portal opens late",
  "ACH batch with static",
  "stock quote from the attic",
  "card decline says maybe",
  "spreadsheet cell owes rent",
  "exchange rate wearing mittens",
  "payee name changed masks",
  "dividend note in blue ink",
  "gas fee taps the glass",
  "risk score smells metallic",
  "margin call by postcard",
  "cashflow graph leans left",
  "cold wallet under towels",
  "hot wallet forgot breakfast",
  "settlement date after thunder",
  "banking dashboard has crumbs",
  "market cap in a teacup",
  "limit order with elbows",
  "stop loss hums softly",
  "earnings calendar skips Tuesday",
  "receipt matched by moonlight",
  "tax lot wearing sunglasses",
  "quote refresh chews slowly",
  "broker portal whispers hold",
  "staking reward smells minty",
  "yield farm needs boots",
  "invoice paid in buttons",
  "ledger export has lint",
  "reconciliation found a marble",
  "fraud flag waves politely",
  "budget category: tiny storms",
  "watchlist sorted by rumor",
  "KYC form asks for courage",
  "escrow balance under glass",
  "swap quote gets nervous",
  "liquidity pool has ripples",
  "stablecoin feels wobbly",
  "ATM map points underground",
  "wire transfer in lowercase",
  "bank statement smells rainy",
  "credit score sneezed twice",
  "loan widget missing a tooth",
  "mortgage calculator dreams loudly",
  "vault icon clicks at dusk",
  "payment rail bends north",
  "token price wearing socks",
  "candlestick chart by candlelight",
  "market open with static",
  "closing bell under carpet",
  "index fund full of echoes",
  "ETF tile says brb",
  "bond ladder needs polish",
  "coupon rate winks once",
  "treasury yield in a jar",
  "options chain rattles softly",
  "strike price painted red",
  "put spread smells like toast",
  "call option calls back",
  "volatility smile missing teeth",
  "beta value took lunch",
  "alpha report in crumbs",
  "P and L wearing a hat",
  "drawdown chart looks seasick",
  "allocation pie got lumpy",
  "rebalance prompt rings twice",
  "cash sweep under the rug",
  "expense tracker sees ghosts",
  "subscription charge from fog",
  "merchant code: SMALL-DOOR",
  "invoice memo says shhh",
  "payment link opens a cupboard",
  "QR code owes coffee",
  "block explorer found socks",
  "mempool crowded with chairs",
  "nonce counter forgot itself",
  "seed phrase in a raincoat",
  "hardware wallet blinks amber",
  "airdrop claim smells official",
  "bridge fee crossing puddles",
  "chain selector points sideways",
  "NFT floor under repair",
  "token approval feels itchy",
  "smart contract says hello",
  "oracle price in pajamas",
  "DAO treasury counts spoons",
  "governance vote by lantern",
  "slippage warning gets louder",
  "perp funding taps its foot",
  "liquidation level glows faintly",
  "order book has whispers",
  "depth chart folds itself",
  "market maker left crumbs",
  "spread widens after midnight",
  "ticker symbol: WOBL",
  "ticker symbol: FOGX",
  "ticker symbol: BEEP",
  "ticker symbol: MOON",
  "ticker symbol: VLT",
  "ticker symbol: IOU",
  "alert when bananas cross",
  "alert above sleepy resistance",
  "resistance line smells burnt",
  "Fibonacci level found keys",
  "moving average took a nap",
  "RSI is very dramatic",
  "MACD crossing with manners",
  "VWAP mutters in cents",
  "earnings beat by one spoon",
  "guidance cut with scissors",
  "analyst note under the mat",
  "buy rating in pencil",
  "sell rating wearing goggles",
  "hold rating holds breath",
  "invoice due before fog",
  "past due but charming",
  "net terms: thirty-ish",
  "payment failed with confetti",
  "refund queued behind thunder",
  "payout pending in slippers",
  "settlement report smells crisp",
  "bank feed duplicate twins",
  "currency selector picks plaid",
  "FX widget stuck on kiwi",
  "savings goal named basement",
  "rainy day fund leaks",
  "round-up rule caught nickels",
  "cashback reward in crumbs",
  "card vault under moonlight",
  "ledger balance says probably",
];
