export const foodDeliveryAndRestaurants: string[] = [
  "taco cart remembers your umbrella",
  "reserve a booth under the fake lemon tree",
  "driver approaching with suspicious soup",
  "menu photo taken during a power blink",
  "extra sauce checkbox hums politely",
  "loyalty stamp shaped like a tiny stove",
  "table for two near the apology fern",
  "kitchen status: noodles thinking",
  "coupon code CRISP-ORB still works",
  "pickup shelf labeled almost yours",
  "five stars for brave napkins",
  "delivery window: before the bread sighs",
  "chef special written on a receipt cloud",
  "grocery basket contains one heroic melon",
  "takeout portal asks for spoon courage",
  "reservation bell rings in lowercase",
  "sushi tracker stuck at seaweed phase",
  "add fries to calm the cart",
  "review says the lasagna knew my name",
  "driver note: avoid the dramatic mailbox",
  "menu tab opens with warm static",
  "free dumpling after nine quiet orders",
  "kitchen printer spits confetti onions",
  "book the corner table by rumor",
  "breakfast burrito dispatch pending",
  "coupon drawer smells like basil",
  "delivery fee includes tiny thunder",
  "order again from the vanished cafe",
  "grocery slot reserved by moonlight",
  "restaurant map shows soup district",
  "burger combo includes one mysterious wink",
  "waitlist number written on toast",
  "spice level: cardigan fire",
  "takeaway bag sealed with prophecy tape",
  "loyalty card missing its last noodle",
  "chef recommends the diagonal ravioli",
  "pizza tracker enters cheese weather",
  "review photo includes a nervous fork",
  "curbside pickup by the blue vent",
  "table booking confirmed after the gong",
  "market order packed beside the parsley",
  "sandwich queue bends around lunch",
  "soup of the day: corridor tomato",
  "driver has your noodles and questions",
  "menu filter set to crunchy ghosts",
  "half off wings during quiet hail",
  "bar tab syncs with the moon calendar",
  "add avocado, summon receipt moth",
  "grocery substitution: regal cucumber",
  "kitchen display blinks amber gravy",
  "reservation notes mention squeaky candles",
  "review badge says mostly delicious",
  "hot pot slot expires at sunset",
  "takeout window opens behind the mural",
  "dessert menu folded into a map",
  "delivery pin dropped on the bread aisle",
  "coupon expired but smells hopeful",
  "no-contact order left by the cactus",
  "chef's kiss detected in checkout",
  "brunch wait time: twelve pancakes",
  "loyalty points ferment overnight",
  "cart contains forbidden croutons",
  "table six requests quieter olives",
  "milk run routed through the deli fog",
  "order status: sauce in transit",
  "review reply from the polite toaster",
  "book patio seating before the chairs migrate",
  "kitchen rail full of tiny tickets",
  "combo meal named after a parking meter",
  "delivery app pings in noodle code",
  "market basket sorted by soup weight",
  "menu says seasonal, means Tuesday",
  "pickup code printed on a pickle",
  "coupon stack leans toward dessert",
  "ramen queue warmed by soft neon",
  "driver found the side door oracle",
  "table deposit held in bread crumbs",
  "one tap reorder from the moon diner",
  "grocery cart suggests suspicious parsley",
  "kitchen timer argues with the salad",
  "reviewer recommends the haunted aioli",
  "takeout lane blocked by heroic steam",
  "reserved booth smells like fresh receipts",
  "delivery route avoids the noodle puddle",
  "menu item: secret basement fries",
  "loyalty stamp earned for quiet chewing",
  "coupon banner follows the soup",
  "chef note: more basil, fewer omens",
  "book high chair near the tiny chandelier",
  "pizza size: municipal large",
  "grocery delivery arrives with proud celery",
  "order tracker shows grill constellation",
  "review count stuck at deliciously odd",
  "curbside slot waits under awning three",
  "dessert add-on glows faintly",
  "cashier portal knows your sandwich history",
  "kitchen status: fryer contemplating",
  "delivery tip rounded by a shy algorithm",
  "waitlist text says bring optimism",
  "menu category: breakfast after dark",
  "coupon wallet full of warm riddles",
  "grocery picker chose the loud bananas",
  "reservation calendar smells like espresso",
  "takeout bag number seven is breathing",
  "driver photo includes heroic cupholders",
  "review says noodles arrived philosophical",
  "stamp card unlocked the bronze spoon",
  "order note: ring bell twice for tacos",
  "daily special hides behind the basil",
  "booking widget dreams of window seats",
  "sauce packet inventory has feelings",
  "delivery ETA measured in garlic moons",
  "market checkout asks about ripe thunder",
  "kitchen screen shows sandwich migration",
  "coupon applies only to brave dumplings",
  "table map rotates toward the fryer",
  "pickup portal whispers order ninety",
  "review stars arranged like spilled salt",
  "loyalty tier: golden spatula cloud",
  "grocery receipt folded around a lime",
  "brunch reservation guarded by syrup",
  "chef special arrives wearing steam",
  "delivery chat says the curry is near",
  "takeout menu laminated by rain",
  "restaurant profile features the old espresso bell",
  "cart recovery email smells like pizza",
  "kitchen status: plating the moon salad",
  "coupon code NOODLE-LADDER unlocked",
  "book communal table beside the fake aquarium",
  "driver leaves pho at the polite gate",
  "grocery substitution refused by the tomato",
  "review draft saved under napkin mode",
  "order total includes invisible garnish",
  "pickup shelf glows behind counter three",
  "menu carousel spins toward late soup",
  "loyalty stamp appears after the biscotti",
  "table ready when the pager becomes quiet"
];
