export const forumsAndWikis: string[] = [
  "sticky thread warns about moon firmware",
  "wiki stub needs three reliable ghosts",
  "moderator banner smells like warm phpBB",
  "talk page debates the sandwich timeline",
  "accepted answer quotes a broken toaster",
  "changelog says fixed maybe for real",
  "knowledge base article still mentions Netscape",
  "edit history blames anonymous cafeteria",
  "forum signature contains seven retired badges",
  "FAQ entry answers a different century",
  "thread necromancer apologizes in advance",
  "rollback note says vandalism or jazz",
  "admin notice requests fewer haunted polls",
  "Q and A bounty paid in confusion",
  "wiki infobox lists height as seasonal",
  "support article updated after lunch incident",
  "old thread locked for excessive prophecy",
  "moderation queue pings the night shift",
  "diff view highlights one suspicious comma",
  "template page transcludes a tiny argument",
  "user talk page asks for receipts",
  "forum avatar replaced by missing trophy",
  "answer edited to remove weather claims",
  "category page contains one lonely subcategory",
  "release notes bury the apology section",
  "KB search suggests restarting the kettle",
  "phpBB rank says junior archivist deluxe",
  "wiki redirect points at a rumor",
  "post preview renders only committee dust",
  "moderator note cites rule 0.5",
  "thread title solved but actually cursed",
  "edit summary says capitalization emergency resolved",
  "reference needed after every potato claim",
  "forum poll has option number negative one",
  "help center breadcrumb loops through 2009",
  "talk page consensus achieved by exhaustion",
  "Q and A comment asks for logs",
  "change log entry forgot the change",
  "wiki page protected from enthusiastic cousins",
  "announcement thread pinned since beta winter",
  "moderation banner says please stop summoning bots",
  "revision compare reveals stealthy typo migration",
  "faq accordion refuses to open Tuesdays",
  "user badge granted for suspicious patience",
  "forum footer powered by basement lightning",
  "article stub about unverified hallway protocol",
  "deleted answer still wins the argument",
  "maintenance notice posted inside maintenance notice",
  "topic tag renamed to miscellaneous thunder",
  "old wiki skin creaks in frames",
  "support forum thread ends with never mind",
  "edit war pauses for server migration",
  "knowledge base screenshot contains a cat hair",
  "moderator lock reason marked seasonal flooding",
  "Q and A sidebar recommends elder thread",
  "wiki table sorts by imaginary smell",
  "changelog date written as later-ish",
  "forum search finds every word except yours",
  "talk archive boxed by a careful librarian",
  "reply button hidden under cookie diplomacy",
  "revision tag says likely not a bicycle",
  "admin bulletin requests lowercase panic only",
  "thread moved to better attic",
  "citation bot rejects the moon source",
  "manual page explains deprecated button ritual",
  "forum smiley pack includes taxable shrug",
  "answer score stuck at polite zero",
  "wiki disambiguation lists three identical hats",
  "site notice apologizes for yesterday forever",
  "edit conflict eats the final paragraph",
  "FAQ says consult your local maintainer",
  "moderation log redacts the interesting noun",
  "release note thanks unnamed spreadsheet hero",
  "forum post begins with long time lurker",
  "wiki talk header asks for calm fonts",
  "KB article marked applies to nobody",
  "Q and A duplicate target vanished",
  "thread split due to kettle digression",
  "article history includes suspicious midnight flourish",
  "admin panel auto-bans the welcome bot",
  "changelog bullet points at itself",
  "phpBB breadcrumb enters forum basement",
  "wiki sandbox full of careful nonsense",
  "moderator edit removes ceremonial all caps",
  "help article footnote denies liability",
  "accepted answer starts with depends wildly",
  "locked topic preserved for training purposes",
  "diff says line moved for vibes",
  "template warning overlaps the other warning",
  "community portal needs volunteers and tape",
  "forum rank promoted to senior lurker",
  "Q and A tag wiki smells dusty",
  "release history skips version 4 out of caution",
  "talk page section renamed after truce",
  "knowledge base table missing Thursday",
  "user page contains retired modem noises",
  "moderation queue labels comment as soup",
  "wiki bot signs with dramatic timestamp",
  "thread reply quotes the entire manual",
  "answer comment says cannot reproduce fog",
  "sitewide banner asks who moved the glossary",
  "changelog archive lives under old stuff",
  "forum attachment named final_final_scroll.png",
  "wiki citation points to dead brochure",
  "admin note added by tired volunteer",
  "Q and A edit improves the question into mist",
  "talk page consensus marked provisional forever",
  "support KB says clear cache twice politely",
  "moderator warning issued for decorative spam",
  "thread index counts posts in crumbs",
  "revision history names only anonymous elevator",
  "wiki navbar still links to guestbook",
  "forum announcement uses emergency beige",
  "duplicate question closed as historically spicy",
  "manual changelog references the wrong manual",
  "template doc includes forbidden workaround",
  "edit summary claims tiny factual broom",
  "knowledge base hero image failed gracefully",
  "user talk archive sorted by bewilderment",
  "old forum theme loads one pixel at a time",
  "moderation banner requests no more chair theories",
  "Q and A bounty expires during explanation",
  "wiki page marked neutral except Tuesdays",
  "forum thread reopened by procedural weather",
];
