export const gamingAndEsports: string[] = [
  "launcher queue estimates one heroic minute",
  "patch notes buff the suspicious barrel",
  "bracket seed lost to hotel wifi",
  "guild motd asks who stole raid spoons",
  "achievement unlocked for tactical loitering",
  "server browser lists only haunted dustbowl",
  "loot page previews uncommon pocket thunder",
  "stream overlay forgets the caster names",
  "clan forum sticky bans prophecy macros",
  "ranked lobby smells like burnt cooldowns",
  "download paused at ninety nine courage",
  "tournament admin pings the wrong captain",
  "boss guide recommends emotional strafing",
  "patch hotfix nerfs ceremonial door kick",
  "guild bank tab labeled do not lick",
  "map vote stuck on lunar warehouse",
  "kill feed credits the snack table",
  "season pass includes decorative regret tokens",
  "match history says victory by paperwork",
  "launcher news carousel mentions ancient beta",
  "esports desk overlays bracket spaghetti",
  "quest log asks for three legal mushrooms",
  "achievement badge shaped like confused chrome",
  "server rules forbid accordion griefing",
  "loot crate contains mildly ranked socks",
  "old clan site still autoplays MIDI",
  "spectator cam follows a brave crate",
  "patch note says grass now negotiates",
  "guild roster marks healer as probably awake",
  "bracket reset caused by chair dispute",
  "stream title says scrims after tacos",
  "mod page requires vintage DirectX optimism",
  "matchmaking found eleven identical captains",
  "launcher repair scans the emotional files",
  "rare drop table lists pocket avalanche",
  "raid calendar conflicts with moon maintenance",
  "finals lobby waiting for certified wizard",
  "leaderboard filters by honorable chaos",
  "server ping reads spiritually nearby",
  "patch notes thank unpaid ladder goblin",
  "arena announcer mispronounces every sponsor",
  "guild application asks favorite siege vegetable",
  "achievement pop-up blocks the actual achievement",
  "loot preview rotates with legal menace",
  "community post demands vanilla ladder amnesty",
  "scrim code expires during team huddle",
  "game launcher requests one more launcher",
  "champ select bans the lunch meta",
  "server browser tag says friendly-ish",
  "patch diff contains forbidden waffle tech",
  "guild raid notes mention elevator phase",
  "stream overlay shows damage per apology",
  "bracket page prints winner in lowercase",
  "cosmetic bundle includes anxious visor",
  "old forum sig tracks LAN victories",
  "patch day login queue reaches folklore",
  "rank emblem looks like damp geometry",
  "server motd says crouch before taxes",
  "achievement guide skips the weird button",
  "loot page odds displayed in moon math",
  "broadcast lower third names the intern",
  "guild hall plaque honors absent tank",
  "mod launcher patched by neighborhood oracle",
  "bracket tiebreaker settled with coin lag",
  "quest reward grants certified pocket fog",
  "server browser hides full servers politely",
  "patch note adds louder inventory silence",
  "clan war recap blames printer latency",
  "stream alert screams about common boots",
  "season ladder frozen for dramatic audit",
  "launcher login says token took scenic route",
  "old guild portal welcomes Netscape raiders",
  "boss timer drifted into next Tuesday",
  "achievement name redacted for snack reasons",
  "loot roll lost to ceremonial one",
  "caster desk debates acceptable barrel routes",
  "server mod list includes potato physics",
  "patch notes fix invisible visible hats",
  "guild officer note says no hallway pulls",
  "bracket overlay uses emergency fonts",
  "match replay corrupt but emotionally accurate",
  "launcher splash screen advertises yesterday",
  "ranked queue dodged by mysterious toaster",
  "community ladder archived under brave nonsense",
  "loot shop rotates in suspicious silence",
  "stream chat unlocks subscriber foghorn",
  "patch note says frogs respect cover",
  "guild recruitment banner promises medium competence",
  "server browser sorting by vibes failed",
  "semifinal pause blamed on headset soup",
  "achievement icon clipped through victory",
  "launcher cache contains ancient clan drama",
  "map pool removes small blue corridor",
  "loot history shows seven unlucky capes",
  "old fansite awards tiny pixel swords",
  "esports bracket names team as pending",
  "patch tooltip lies with confidence",
  "guild raid marker placed on accountant",
  "server password hint says ask Brent",
  "stream overlay stuck on warmup forever",
  "achievement unlocked after respectful crouch",
  "launcher beta branch called whoops",
  "loot bundle discounted by haunted coupon",
  "community cup finals delayed by patch",
  "server browser region set to basement",
  "patch notes remove duplicate duplicate armor",
  "guild wiki documents forbidden jump route",
  "caster cam catches tactical sandwich",
  "bracket admin swaps teams alphabetically badly",
  "quest tracker points below the floor",
  "rare mount named reasonably fast chair",
  "launcher changelog apologizes for launcher",
  "old gaming forum counts posts in frags",
  "match stats include objective hugs denied",
  "server rules allow tasteful rocket jumps",
  "patch note buffs corner peeking regret",
  "guild calendar timezone set to LAN",
  "loot page thumbnail missing one boot",
  "stream scoreboard says game five-ish",
  "achievement text wraps into tiny panic",
  "bracket grand final sponsored by ping",
  "mod readme demands fresh ritual drivers",
  "launcher download speed measured in crumbs",
  "server browser favorite renamed to home",
];
