export const governmentAndLegal: string[] = [
  "permit portal remembers last Tuesday",
  "clerk stamp pending in tray C",
  "court calendar opens with a cough",
  "benefits login asks for mailbox color",
  "tax form page reloads politely",
  "public notice taped under public notice",
  "zoning affidavit smells like toner",
  "case lookup lost the middle initial",
  "compliance checklist has checkbox feelings",
  "license renewal waits behind glass",
  "record request routed to drawer seven",
  "hearing room calendar shows maybe",
  "official notice uses heroic staples",
  "appeal form requests exact sidewalk",
  "benefits portal thanks applicant twice",
  "tax worksheet hums near line 12",
  "permit fee table leans left",
  "court docket sorts by moonlight",
  "agency homepage features empty lectern",
  "ordinance archive skips the loud page",
  "filing receipt printed with confidence",
  "compliance matrix contains tiny soup",
  "public record export arrives wearing tabs",
  "summons template asks for room smell",
  "license page requires blue ink memory",
  "inspection notice cites basement Tuesday",
  "registry search returns one tired comma",
  "benefit eligibility wizard spins slowly",
  "tax portal verifies shoe size indirectly",
  "municipal code opens to appendix fog",
  "case status says administratively sleepy",
  "permit checklist requests unobstructed clipboard",
  "official seal rendered as gray potato",
  "notice period begins after bell",
  "public records cart contains archived dust",
  "courtroom directory points at elevator",
  "form 8B asks for prior rectangle",
  "compliance attestation awaits supervisor initials",
  "agency banner says service interrupted softly",
  "hearing notice mailed by cautious printer",
  "tax schedule hides behind continuation sheet",
  "benefits dashboard shows pending umbrella",
  "land records map blinks at parcel",
  "court calendar lists ceremonial lunch",
  "permit number includes two brave zeros",
  "official bulletin corrected without eye contact",
  "legal form footer forgot the county",
  "compliance reminder arrives pre-overdue",
  "case search filters by hallway",
  "public notice board has laminate wrinkles",
  "tax transcript queue considers itself",
  "licensing portal rejects decorative hyphen",
  "benefits upload accepts grayscale sandwich",
  "inspection checklist mentions ordinary ladder",
  "records office closes for stamp inventory",
  "court clerk note says bring patience",
  "filing portal opens in civic beige",
  "ordinance PDF rotated by tradition",
  "permit application asks whether sign exists",
  "compliance checklist line item 4ish",
  "public hearing livestream shows microphone chair",
  "case calendar delayed by docket drizzle",
  "tax payment receipt has stern margins",
  "benefit notice includes mysterious enclosure",
  "official notice updated after tape failure",
  "record search needs parcel whisper",
  "court form asks for legible silence",
  "license renewal confirmation arrives sideways",
  "permit tracker stuck on preliminary final",
  "compliance portal wants quarterly shrug",
  "public records request estimates forever",
  "tax form help text points upstairs",
  "agency directory lists interim stamp lead",
  "court docket archived under miscellaneous noon",
  "benefits page warns of session evaporation",
  "official notice cites page not found",
  "land use memo references historic curb",
  "permit desk accepts exact change weather",
  "legal filing cover sheet tastes numeric",
  "compliance checklist confirms binder location",
  "public record preview shows one pixel",
  "court calendar has three canceled rooms",
  "tax portal security question remembers bridge",
  "benefits account locked for dramatic reasons",
  "notice of notice posted for noticing",
  "registry form demands applicant rectangle",
  "permit workflow waits for chair approval",
  "case lookup says docket taking break",
  "official records index loves abbreviations",
  "compliance affidavit stored near copier",
  "hearing agenda lists variance for awning",
  "tax form line 27b looks nervous",
  "benefits portal prints eligibility fog",
  "public notice PDF has municipal crumbs",
  "license board agenda adds forgotten gavel",
  "permit expiration date feels provisional",
  "court portal captcha asks for stapler",
  "records request receipt folded digitally",
  "compliance task due after second bell",
  "agency status page says mostly open",
  "tax account summary contains cautious cents",
  "benefit recertification checklist wants proof",
  "legal form dropdown offers other other",
  "public records export named final_final",
  "court calendar refresh loses room 204",
  "permit page confirms sidewalk maybe permitted",
  "official bulletin sorts by ancient fax",
  "compliance dashboard shows amber rectangle",
  "tax notice envelope shown for reference",
  "benefits inbox includes unread explanation",
  "case filing queue smells electronic",
  "license lookup finds expired enthusiasm",
  "record portal requests certified patience",
  "court notice says appear by screen",
  "permit conditions include ordinary daylight",
  "compliance reminder uses serious blue",
  "public meeting notice lacks a chair",
  "tax form attachment named attachment",
  "benefit portal asks for household maybe",
  "official form saves under temporary permanent",
  "docket search finds case adjacent",
  "records archive displays ceremonial loading",
  "permit receipt thanks the applicant quietly",
];
