export const jobsAndRecruiting: string[] = [
  "job board sorted by quiet panic",
  "resume objective mentions weatherproof teamwork",
  "applicant portal forgot your middle initial",
  "recruiter ping arrives wearing loafers",
  "shift swap approved by the mop closet",
  "career page loads a tiny handshake",
  "cover letter addressed to hiring cloud",
  "payroll tab smells like toner",
  "onboarding checklist asks for favorite stapler",
  "job alert for basement strategist",
  "interview calendar invites the wrong Tuesday",
  "benefits PDF has a loose tooth",
  "workplace intranet whispers dress code",
  "candidate profile saved as nearly complete",
  "time clock blinks at overtime",
  "referral bonus hidden behind fern",
  "ATS score says charming but unparseable",
  "resume bullet chases a metric",
  "apply button wants eye contact",
  "job requisition wearing temporary shoes",
  "team page lists four mysterious Steves",
  "corporate careers hero smells laminated",
  "offer letter awaiting moon approval",
  "pay stub includes tiny thunder",
  "availability grid dislikes Wednesdays",
  "recruiter voicemail full of confetti",
  "skills section claims advanced ladder",
  "background check lost its clipboard",
  "candidate status: orbiting manager",
  "shift bid opened before sunrise",
  "manager note says promising elbows",
  "job description allergic to verbs",
  "interview scorecard asks about soup",
  "I-9 form dreams in boxes",
  "training module stuck on sincerity",
  "employee portal remembers your locker",
  "resume template from another decade",
  "salary range wearing a trench coat",
  "screening question has stage fright",
  "career fair booth smells electric",
  "recruiting funnel shaped like a spoon",
  "job saved to pocket universe",
  "application draft older than chair",
  "orientation agenda starts with fog",
  "timesheet row refuses to total",
  "direct deposit page hums softly",
  "talent pool warmed by desk lamp",
  "interviewer feedback written sideways",
  "candidate email says circle back soonish",
  "role title includes accidental wizardry",
  "job board badge says urgently gentle",
  "new hire packet stapled to air",
  "payroll exception needs a witness",
  "shift scheduler sneezes duplicates",
  "resume upload chews the header",
  "careers search finds only lunch",
  "application confirmation in lowercase",
  "recruiter sequence skips step goose",
  "office location marked near the printer",
  "interview loop gained a hallway",
  "employee handbook denies the basement",
  "candidate source listed as weather",
  "job alert subject says psst",
  "workday task smells freshly clicked",
  "badge photo pending legal review",
  "open role hiding behind procurement",
  "resume gap explained by tides",
  "onboarding buddy assigned by raffle",
  "pay grade labeled maybe seven",
  "career site cookie asks about ambition",
  "hiring manager marked out of office",
  "screening call under fluorescent suspense",
  "calendar hold shaped like a ladder",
  "offer approval stuck in finance fog",
  "internship posting with tiny cape",
  "break room policy linked from payroll",
  "candidate tag says reliable socks",
  "job board filter: remote adjacent",
  "resume summary too awake",
  "employment history smells like staples",
  "applicant portal spins a brass wheel",
  "recruiter message includes one breadcrumb",
  "shift premium glows after midnight",
  "corporate intranet has hallway breath",
  "welcome email addressed to future you",
  "tax form folded into quarters",
  "job family tree loses an uncle",
  "benefits enrollment opens reluctantly",
  "candidate pipeline leaks confetti",
  "interview panel named after snacks",
  "resume parser fears bullet points",
  "careers footer lists brave fax number",
  "background consent checkbox sighs",
  "time off balance includes prophecy",
  "training quiz asks about laminators",
  "payroll calendar misses leap lunch",
  "job post promises dynamic carpeting",
  "application status says manager thinking",
  "recruiter follow-up arrives in beige",
  "shift note: bring extra patience",
  "employee directory sorted by cardigan",
  "new hire portal needs a nap",
  "offer packet smells like rain",
  "resume filename final_final_really_final",
  "candidate survey rates the elevator",
  "job requisition escaped approval",
  "careers chatbot recommends accounting cave",
  "onboarding step zero blinks",
  "pay statement hides a nickel",
  "interview prep deck squeaks",
  "shift calendar marks mystery coverage",
  "workplace announcement uses bold thunder",
  "applicant login remembers old hope",
  "reference check calls the vending machine",
  "resume keyword density tastes metallic",
  "job board map pins a rumor",
  "recruiter DM says quick question forever",
  "career path diagram bends left",
  "employee portal password expires at lunch",
  "compliance training unlocks the broom",
  "candidate note: excellent folder energy",
  "payroll admin wearing spreadsheet perfume",
  "shift request approved by moonlight",
  "corporate careers site loads applause",
];
