export const mapsAndLocalDiscovery: string[] = [
  "turn left where the bakery pin looks nervous",
  "coffee nearby sorted by chair wobble index",
  "saved place moved behind the bus shelter",
  "parking garage accepts coins and minor prophecies",
  "review says five stars for the alley shortcut",
  "weather layer shows drizzle over aisle seven",
  "directions avoid stairs and suspicious fountains",
  "map pin dropped into the soup district",
  "transit arrival estimates one ceremonial delay",
  "directory listing verified by a lonely awning",
  "nearby pharmacy open until the moon blinks",
  "route recalculating around a parade of cones",
  "search results include a very confident bench",
  "favorite plaza renamed in the last update",
  "parking meter hums under saved destinations",
  "bike route follows the polite canal",
  "reviewer mentions excellent napkin geography",
  "satellite view caught the plaza mid-yawn",
  "local guide badge smells like hot asphalt",
  "bus stop hidden behind three tiny reviews",
  "open now filter ignores the haunted kiosk",
  "walking time adjusted for dramatic headwinds",
  "map labels the shortcut as community folklore",
  "table for two near the historic crosswalk",
  "curbside pickup pin facing the wrong era",
  "traffic layer reports syrup near the overpass",
  "train platform changed to the echoing one",
  "saved list titled places with unreliable doors",
  "public restroom marker requires emotional stamina",
  "turnaround point is the orange vending machine",
  "neighborhood page lists four legendary mailboxes",
  "review photo contains mostly ceiling and regret",
  "accessible entrance behind the third umbrella",
  "local search suggests soup within walking distance",
  "pin cluster expands into an argument",
  "night mode makes the courthouse look shy",
  "parking lot full except for imaginary spaces",
  "weather radar paints fog over the dog park",
  "directions begin at your previous confusion",
  "tram line paused for a tunnel rehearsal",
  "directory category includes locksmiths and feelings",
  "map saved the old cinema twice",
  "review summary praises the reliable side door",
  "route preview crosses a suspiciously clean bridge",
  "charging station behind the retired taco sign",
  "nearby museums ranked by gift shop humidity",
  "pin note says meet under the blinking crane",
  "indoor map shows a corridor named later",
  "bus arrival floats beside the noodle shop",
  "parking validation available after a small riddle",
  "traffic jam shaped like a question mark",
  "local page claims the fountain is seasonal",
  "directions avoid tolls rumors and steep vibes",
  "coffee shop hours updated by a sleepy owner",
  "saved pins glow in the wrong neighborhood",
  "review filter removes complaints about the carpet",
  "hail overlay covers the miniature golf course",
  "street view remembers a vanished sandwich board",
  "turn right after the municipal planter sighs",
  "delivery entrance listed under soft mysteries",
  "bike parking near the blue uncertain mural",
  "subway exit opens into yesterday's plaza",
  "near me search finds three apologetic dentists",
  "map legend includes puddle and almost puddle",
  "restaurant page still mentions faxed reservations",
  "walk score lowered by one cursed escalator",
  "saved trip includes a bathroom with opinions",
  "reviewer recommends the northern door only",
  "parking entrance tucked below the brass arrow",
  "weather alert follows you through the arcade",
  "route options prefer scenic loading docks",
  "local directory says cash only on windy days",
  "map pin refuses to leave the median",
  "transit card balance near the lemonade stand",
  "nearby florist closed for inventory emotions",
  "street closure drawn with excessive confidence",
  "review stars wobble over the lunch counter",
  "search this area button looks personally offended",
  "saved beach pin renamed cold sandwich point",
  "parking level b smells like route history",
  "turn left after the mural of accountants",
  "weather overlay predicts suspiciously local thunder",
  "grocery listing has nineteen aisle photos",
  "bus bay moved beside the quiet statue",
  "directory map loads every chiropractor at once",
  "navigation voice whispers about the old detour",
  "popular times spike during mysterious bell hour",
  "pin dropped between two identical nail salons",
  "review says clean restroom brave wallpaper",
  "ferry timetable taped to the digital map",
  "parking app remembers your least favorite curb",
  "nearby parks sorted by bench sincerity",
  "route shared with the wrong picnic blanket",
  "local page badge says owner sometimes responds",
  "rain layer misses the puddle under you",
  "crosswalk timer appears in saved notes",
  "search result sponsored by a confusing fountain",
  "transit delay explained as signal contemplation",
  "map shows a hotel inside the roundabout",
  "directions continue through the polite loading zone",
  "review photo proves the fries were vertical",
  "curb color legend hidden behind parking grief",
  "nearby hardware store sells emergency umbrellas",
  "saved list duplicates every place with soup",
  "walking route climbs the ceremonial driveway",
  "weather tile says wind near the courthouse",
  "local business hours depend on chalkboard mood",
  "train exit marked by the glowing pretzel",
  "map label overlaps the famous pothole",
  "parking reminder chirps from the glovebox",
  "review mentions quiet corner and loud wallpaper",
  "nearby tacos filtered by distance from regret",
  "directions reroute through a legal hallway",
  "saved pin says do not trust this bench",
  "storm overlay covers the entire farmers market",
  "directory page lists elevators as landmarks",
  "transit transfer timed for heroic jogging",
  "street view blurs the suspicious sandwich",
  "parking lot entrance after the second moon sign",
  "local guide notes the shortcut floods politely",
  "map cache contains one obsolete carousel",
];
