export const realEstateAndHousing: string[] = [
  "sunny unit above the mailbox archive",
  "two bedrooms near the cautious stairwell",
  "mortgage widget asks about your shed dreams",
  "open house starts when the porch light agrees",
  "floor plan includes one ceremonial nook",
  "HOA notice taped to the decorative silence",
  "rental application wants three previous doorbells",
  "property map pin hiding behind the tool shed",
  "inspection report smells faintly of attic dust",
  "landlord form requests your favorite smoke alarm",
  "studio apartment with ambitious closet weather",
  "pre approval letter folded into a tiny lawn",
  "garage access pending gate remote negotiations",
  "lease portal remembers your unpaid hallway",
  "condo bylaws forbid suspiciously tall planters",
  "listing photos taken from the brave corner",
  "basement suite includes seasonal pipe music",
  "zoning overlay whispers beside the driveway",
  "tenant screening paused near the blue checkbox",
  "escrow status blinking in the breakfast area",
  "backyard described as mostly theoretical grass",
  "rent estimate drifts toward the linen closet",
  "property tax card found under the welcome mat",
  "walk score counted the wrong sidewalk",
  "virtual tour stuck inside the pantry",
  "title search found a sleepy easement",
  "duplex listing with reversible fence opinions",
  "inspection window booked after the cupboard moon",
  "security deposit stored in a polite envelope",
  "mortgage rate slider squeaks at five percent",
  "kitchen island visible from the listing typo",
  "HOA portal rejects unapproved mailbox vibes",
  "apartment filter set to haunted laundry",
  "rental history fits inside one coat hook",
  "property manager replies through the intercom fog",
  "roof age estimated by neighborhood legend",
  "utility disclosure missing the tiny thunder meter",
  "parking spot assigned by ancient spreadsheet",
  "listing agent notes the courageous backsplash",
  "floor plan labels a room as maybe",
  "eviction check returned a confused door knocker",
  "mortgage calculator wearing beige socks",
  "pet policy mentions cats and procedural pumpkins",
  "balcony square footage includes one nervous fern",
  "map layer shows schools and mysterious hedges",
  "inspection checklist fears the crawlspace",
  "renters insurance checkbox under the loose tile",
  "home value chart leans into the mailbox",
  "shared laundry requires ceremonial quarters",
  "landlord portal archived the leaky Tuesday",
  "buyer packet smells like fresh drywall",
  "closing costs lined up beside the thermostat",
  "unit 3B has an optimistic radiator",
  "property tour begins at the inaccurate fountain",
  "application fee paid in perfectly normal dollars",
  "HOA fine issued for rebellious patio chair",
  "credit pull waits behind the screen door",
  "open concept kitchen with shy ceiling fan",
  "yard sign points toward the compliance closet",
  "lease renewal offered with extra beige",
  "deed restriction naps under the county seal",
  "apartment portal forgot the elevator button",
  "seller disclosure lists one thoughtful creak",
  "mortgage escrow bowl contains tiny invoices",
  "vacancy calendar blocked by a large rug",
  "property boundary follows the suspicious tulips",
  "move in checklist includes key and patience",
  "inspection photo catches the cabinet blinking",
  "rent concession expires before the lobby fern",
  "house number verified by sidewalk gossip",
  "listing headline promises dramatic mudroom energy",
  "co op board seeks emotional references",
  "floor plan rotated toward the linen mystery",
  "rental portal asks if windows are witnesses",
  "mortgage payoff quote arrives with lint",
  "property map measures distance in doormats",
  "tenant ledger found one misplaced February",
  "HOA meeting agenda includes fence feelings",
  "home inspection notes a philosophical gutter",
  "apartment search sorted by suspicious carpet",
  "lease addendum covers balcony wind etiquette",
  "title company calls from the copier room",
  "walkthrough form checked the wrong closet",
  "open house cookies guard the disclosures",
  "loan estimate hides behind the foyer plant",
  "rental application asks for landlord latitude",
  "zillow style estimate coughs politely",
  "property card lists basement as ambitious",
  "inspection contingency folded into the junk drawer",
  "common area notice laminated by moonlight",
  "unit availability changes when the awning sighs",
  "security gate code smells like old rain",
  "condo fee covers hallway optimism",
  "house tour pauses at the dramatic banister",
  "mortgage portal refreshes the amortization fog",
  "landlord signature missing near the stapler",
  "apartment amenities include cautious package room",
  "property manager left notes in the elevator",
  "seller credit applied to the squeaky step",
  "floor plan says bedroom if you believe",
  "rental listing verified by a tired key",
  "HOA newsletter celebrates compliant shrubbery",
  "inspection ladder declined the attic invitation",
  "lease packet smells like copier heat",
  "mortgage widget estimates monthly porch emotions",
  "parcel map aligns with the heroic fence",
  "tenant portal shows one pending lightbulb",
  "open house sign survived the drizzle audit",
  "property photos crop out the mailbox argument",
  "application status waits in the vestibule",
  "closing disclosure arrives wearing staples",
  "rental criteria mention income and vibes",
  "condo reserves hidden behind spreadsheet dust",
  "inspection summary praises the resilient doorknob",
  "home search filter set to weirdly sunny",
  "landlord form confirms the boiler has opinions",
  "mortgage prequal banner follows the cursor home",
  "floor plan legend forgot the breakfast wall",
  "HOA assessment mailed to the former cactus",
  "property map zooms into porch uncertainty",
  "rental portal password expires at move in",
  "listing remarks promise tasteful outlet placement",
];
