export const secondhandAndAuctions: string[] = [
  "auction lot smells like basement brass",
  "bid button waits under glass",
  "pickup only after the rain",
  "seller says barely used by ghosts",
  "estate sale starts before coffee",
  "reserve price written in pencil",
  "classified ad with one honest typo",
  "local pickup behind the bowling alley",
  "marketplace chat says is this available",
  "bid page refreshes in tiny coughs",
  "vintage lamp with suspicious confidence",
  "swap group rules pinned crooked",
  "buyer rating: punctual but damp",
  "listing draft saved as maybe chair",
  "cash only, exact thunder preferred",
  "porch pickup beside the sad fern",
  "auctioneer clears throat at dusk",
  "seller badge earned in rain",
  "lot number seven keeps humming",
  "used bookshelf with secret bakery dust",
  "minimum bid includes old receipt",
  "garage sale map folds itself",
  "offer accepted by a nervous toaster",
  "watchlist full of wooden strangers",
  "item condition: charmingly uncertain",
  "local deal expires at noonish",
  "seller notes: no lowballing the moon",
  "bid increment set to one sigh",
  "pickup locker smells like pennies",
  "estate china with calendar anxiety",
  "classifieds footer missing a shoe",
  "counteroffer arrives wearing mittens",
  "auction timer blinking like a porch light",
  "used bike prefers flat streets",
  "meetup spot under the blue sign",
  "rating comment: brought correct rope",
  "listing photo includes mystery elbow",
  "box of cables, probably important",
  "final bid from a silent barn",
  "swap request for two clean hinges",
  "seller profile joined last eclipse",
  "winning bidder lives near fog",
  "pickup window between soup and sunset",
  "estate trunk full of careful buttons",
  "marketplace filter sorted by regret",
  "auction catalog smells like cloves",
  "draft title: old thing, works",
  "buyer asks dimensions in teaspoons",
  "used coat with dramatic pockets",
  "reserve not met, chair relieved",
  "free if collected before Tuesday",
  "seller rating lost one star to mud",
  "bid history includes a racetrack alias",
  "classified headline too brave",
  "local pickup gate code is nope",
  "lot closes when the kettle whistles",
  "secondhand rug remembers parties",
  "swap group admin demands clearer photos",
  "cash drawer filled with small omens",
  "watcher count rises after midnight",
  "estate tools arranged by suspicion",
  "listing draft needs fewer apologies",
  "buyer message: can you hold it",
  "auction invoice folded into thirds",
  "pickup porch marked by yellow bucket",
  "used desk has excellent alibis",
  "seller offers bundle of odd knobs",
  "bid page says going, going, maybe",
  "classified reply from a fax machine",
  "rating badge glows faintly green",
  "local seller near the water tower",
  "estate mirror includes previous opinions",
  "swap for seeds or clean jars",
  "listing category: household mysteries",
  "highest bid from attic user 41",
  "pickup instructions mention the cactus",
  "auction lot of mismatched keys",
  "used stereo only plays afternoons",
  "seller lowered price during thunder",
  "classified ad renewed by mistake",
  "bidder nickname too formal",
  "porch pickup honor box squints",
  "estate sale cashier knows everyone",
  "listing draft stuck on condition",
  "swap group wants no scented candles",
  "buyer feedback: quick, odd, polite",
  "auction preview in the cold shed",
  "secondhand table with one short leg",
  "offer expires when bakery closes",
  "seller says smoke free, cave maybe",
  "bid confirmation arrives in lowercase",
  "local pickup by the green mailbox",
  "estate linens folded like evidence",
  "classifieds sidebar sells tiny anvils",
  "rating score: four moons and change",
  "listing draft includes a measuring spoon",
  "used blender negotiates loudly",
  "auction lot photographed on carpet",
  "swap meet booth number almost thirteen",
  "buyer asks if frame is cursed",
  "seller profile photo is a doorknob",
  "pickup portal rejects cloudy addresses",
  "reserve price under the saucer",
  "estate clock still arguing time",
  "bid page hiccups at final second",
  "classified bundle: lamps, lids, rope",
  "used cabinet smells faintly official",
  "seller notes cash or orchard pears",
  "watchlist item marked unlikely treasure",
  "local pickup no stairs after five",
  "auction clerk mispronounces the vase",
  "swap group post needs a banana for scale",
  "buyer rating: arrived with tarp",
  "listing draft says rare but tired",
  "estate sale sign points indoors",
  "used boots with local knowledge",
  "final offer wrapped in newspaper",
  "marketplace map pins a basement",
  "bidder outbid by kitchen clock",
  "pickup code taped to the gnome",
  "seller response time: three soups",
  "classified ad smells like toner",
];
