export const shortVideoPlatforms: string[] = [
  "for you tunnel opens behind the cereal box",
  "vertical video portal hums in portrait mode",
  "creator ring light argues with the ceiling fan",
  "duet window arrives wearing borrowed eyebrows",
  "stitch starts exactly before the useful part",
  "viral audio coughs from every kitchen drawer",
  "filter gives the dog executive cheekbones",
  "comment pin floats like a tiny courtroom",
  "live gift cannon fires pixel roses at midnight",
  "algorithm recommends soup based on one blink",
  "swipe feed remembers the abandoned dance tutorial",
  "reel caption promises part two inside a maze",
  "shorts shelf stacks tiny dramatic refrigerators",
  "creator fund calculator smells like burnt confetti",
  "green screen host points at yesterday's weather",
  "beauty filter negotiates with the bathroom mirror",
  "sound page contains eight million identical sneezes",
  "remix button glows under the apology video",
  "live chat buys a cartoon whale for clout",
  "recommendation rail follows the thumb home",
  "vertical ad disguises itself as cousin footage",
  "loop seam hides behind a fake gasp",
  "caption bubble mishears every brand name",
  "sticker pack includes legally distinct lightning",
  "reaction cam watches a reaction cam watching",
  "creator bio says email beneath six crowns",
  "draft folder ferments an abandoned lip sync",
  "hashtag soup cools on the discovery table",
  "sound trend expires during the first hand clap",
  "duet chain loops into a tiny parliament",
  "stitch prompt asks where the wizard went",
  "live shopping host sells magnetic soup spoons",
  "gift leaderboard crowned a username made of commas",
  "comment section demands the uncut cucumber footage",
  "algorithmic tunnel chooses forklift ballet next",
  "short video shrine refreshes before the punchline",
  "face tracker loses faith near the forehead",
  "AR hat lands three inches behind grandma",
  "creator watermark survives every repost storm",
  "swipe gesture opens a trapdoor of recipes",
  "micro vlog starts inside a very loud elevator",
  "sound bite becomes municipal law by lunch",
  "reels tab blinks like a vending machine",
  "for you page serves dentist lore again",
  "viewer retention graph drops at the spoon",
  "caption says wait for it after it happened",
  "filter menu offers haunted spreadsheet face",
  "effects tray rattles with chrome butterflies",
  "comment reply becomes a new vertical corridor",
  "pinned comment asks about the ceiling banana",
  "live cohost freezes mid inspirational eyebrow",
  "subscriber badge flickers beside a soup emoji",
  "creator studio reports one mysterious toaster audience",
  "autocaption invents a mayor named Plink",
  "sound sync misses the dramatic shoe reveal",
  "duet split screen trapped a hallway ghost",
  "stitch cutoff turns wisdom into appliance noise",
  "viral dance tutorial begins with legal disclaimers",
  "shorts autoplay digs through the couch algorithm",
  "reel remix puts sunglasses on the tax form",
  "vertical carousel sells attention by the thimble",
  "watch again button knows too much about lunch",
  "comment hearts pile up like digital cereal",
  "live gift train stops at the glitter depot",
  "creator challenge requires one spoon and confidence",
  "algorithm says people like you enjoyed fog",
  "thumb scrolls past a screaming craft tutorial",
  "portal recommends frog facts after finance advice",
  "sound library hides the perfect door creak",
  "face filter adds one ceremonial nostril",
  "speed ramp turns a sandwich into prophecy",
  "micro influencer unboxes a box of pauses",
  "stitch permission buried under dancing terms",
  "duet invitation smells faintly of ring light",
  "viral audio watermark jingles in the wallpaper",
  "short video comments form a tiny jury",
  "swipe feed serves a carousel of elbows",
  "for you altar requests another thirty seconds",
  "creator dashboard applauds suspiciously from beta",
  "live battle timer ticks over pixel fireworks",
  "gift animation covers the apology paragraph",
  "green screen meme points at a blank moon",
  "caption hook says nobody talks about ladders",
  "filter pack includes velvet jaw and tax glow",
  "algorithmic recommendation finds the forbidden muffin niche",
  "reel loops until the dog approves continuity",
  "shorts player hides comments behind a sneeze",
  "duet response brings a second tiny kitchen",
  "stitch rebuttal begins with an ancient doorbell",
  "creator collab splits the screen into weather",
  "viral sound has a landlord now",
  "live moderator deletes the word zucchini twice",
  "comment reply video wears a courtroom hoodie",
  "vertical feed buries the original under sparkles",
  "trend page smells like hot phone glass",
  "filter slider gives everyone historical cheekbones",
  "swipe fatigue arrives carrying miniature ads",
  "recommendation engine mistakes laundry for philosophy",
  "looped clip reveals the same falling spoon",
  "sound reuse graph resembles a tangled necklace",
  "creator tip jar jingles in platform coins",
  "live gifts bounce off the pinned question",
  "short video portal opens during the toast",
  "reels audio tab chants one more edit",
  "caption template begs for the wrong audience",
  "duet grid becomes a neighborhood choir accident",
  "stitch thread follows breadcrumbs into a haircut",
  "filter preview stares back with sponsored freckles",
  "algorithm trains on a single accidental like",
  "watch history remembers the cursed cake flip",
  "creator verification checkmark looks freshly rented",
  "live room title changes during the magic trick",
  "comment war starts over a measuring cup",
  "viral audio loop gets stuck in the elevator",
  "vertical player trims silence into suspense dust",
  "remix credit hides below seventeen hashtags",
  "shorts shelf recommends tactical accordion cleaning",
  "swipe portal eats the last useful afternoon",
  "creator avatar winks from a foam microphone",
  "for you feed predicts a decorative argument",
  "effects button leaks glitter into the search tab",
];
