export const weatherAndEnvironment: string[] = [
  "forecast cone hiding behind a damp accordion",
  "barometer needle points at mild inconvenience",
  "rain radar stitched from green receipt paper",
  "storm warning arrives wearing a plastic poncho",
  "sunrise table forgot the first orange stripe",
  "wind gust chart rattles the municipal spoon drawer",
  "humidity widget sweats onto the login button",
  "pollen map dusted with suspicious yellow confetti",
  "garden planner recommends beans after the moon blinks",
  "tide table folds itself into a wet calendar",
  "air quality index coughs in polite magenta",
  "heat advisory taped beside the frozen fountain",
  "cloud layer opacity set by an absent intern",
  "lightning tracker draws forks over the county fair",
  "hail report includes one dented mailbox witness",
  "dew point reads like a basement postcard",
  "snow depth ruler lost in the ski lodge printer",
  "river gauge murmurs under the bridge widget",
  "coastal flood alert smells like old rope",
  "UV index wears tiny sunglasses indoors",
  "garden frost clock rings inside the lettuce",
  "storm cell named after a missing patio chair",
  "daily high trapped inside the thermometer elevator",
  "marine forecast whispers through a cracked buoy",
  "solar output graph nods at a sleepy inverter",
  "energy dashboard counts watts with cold fingers",
  "mosquito outlook circles the picnic password",
  "leaf wetness sensor dreams of better gutters",
  "precipitation chances tumble from a cloud drawer",
  "drought monitor colored like a tired cereal box",
  "wildfire smoke plume crosses the commute tile",
  "allergy season starts under the carpet map",
  "green roof sensor reports one smug fern",
  "compost temperature rises with bureaucratic patience",
  "soil moisture tile holds a tiny tin cup",
  "freeze warning tucked into the seed packet",
  "weather station battery blinking from the barn roof",
  "fog advisory erases the left side of Tuesday",
  "beach hazard banner flaps in the browser chrome",
  "rip current risk hums inside the surf cam",
  "lake level chart drips onto the footer",
  "reservoir storage shown in anxious blue bars",
  "rain barrel forecast asks for another barrel",
  "orchard chill hours stacked like cold pancakes",
  "irrigation schedule waits for the wind to apologize",
  "dust alert rolls through the suburb dropdown",
  "ozone forecast tastes faintly like bus vinyl",
  "PM2.5 sparkline sneaks under the window seal",
  "indoor air widget blames the toaster quietly",
  "carbon tracker files the sunset under emissions",
  "climate normal wearing last decade's jacket",
  "temperature anomaly waves from a red clipboard",
  "sea level trend climbs the dock ladder",
  "glacier mass chart shrinks in the sidebar",
  "phenology calendar marks budburst with green tape",
  "bird migration layer crosses the night radar",
  "monsoon onset shown by three nervous umbrellas",
  "cyclone watch spins near the pantry door",
  "pressure tendency falls down the station stairs",
  "visibility report squints at the runway lights",
  "aviation ceiling map bumps into low clouds",
  "road ice alert clicks its tiny hazard lights",
  "black ice probability hides under the overpass",
  "snowplow tracker circles the cul de sac",
  "school closure feed smells like wet mittens",
  "power outage map flickers with candle logic",
  "cooling degree days nap inside a spreadsheet",
  "heating degree days stack firewood in pixels",
  "home energy report sighs through the attic vent",
  "demand response event knocks on the thermostat",
  "smart meter graph finds a midnight refrigerator",
  "solar noon indicator stands on the roofline",
  "shade planner rotates the pear tree carefully",
  "lawn watering window guarded by a clay frog",
  "mulch depth reminder taps the garden fork",
  "seedling hardening timer dislikes sudden wind",
  "greenhouse vent opens after the basil negotiates",
  "bee activity forecast buzzes near the save button",
  "mold risk chart blooms behind the laundry room",
  "asthma forecast reads the alley like a diary",
  "ragweed layer clings to the county outline",
  "oak pollen count climbs the old school ladder",
  "grass pollen band rehearses behind the scoreboard",
  "storm siren test scheduled beside the casserole",
  "evacuation zone map creases at the gas station",
  "sandbag pickup listed under civic weather chores",
  "flash flood watch fills the culvert calendar",
  "watershed alert arrives with muddy shoelaces",
  "creek camera refreshes at frog height",
  "snow water equivalent hides in a mountain locker",
  "avalanche bulletin sharpens a careful pencil",
  "ski wax forecast argues with the chairlift",
  "trail mud status sticks to the park kiosk",
  "campfire restriction banner smells like pine smoke",
  "burn ban toggle locked by a dry pinecone",
  "tree canopy map shades the loud intersection",
  "urban heat island tile melts the parking lot",
  "cool roof scorecard reflects a pale afternoon",
  "stormwater drain marker asks for a broom",
  "wetland boundary layer wades across parcel lines",
  "invasive species alert rides a muddy boot",
  "algal bloom notice glows under the boat ramp",
  "shellfish closure table snaps shut at low tide",
  "beach bacteria count frowns at the gulls",
  "drinking water advisory folded into the bill",
  "well level monitor knocks from underground",
  "septic risk map gurgles after heavy rain",
  "noise pollution heatmap shivers near the highway",
  "light pollution atlas dims the backyard stars",
  "dark sky forecast saves one quiet constellation",
  "recycling pickup reminder weighs the thunderstorm",
  "landfill gas chart blips under the hill",
  "methane sensor chirps beside the dairy lane",
  "nitrogen runoff model follows the corn rows",
  "crop evapotranspiration arrives with a dusty hat",
  "pasture growth index chews the dashboard corner",
  "livestock heat stress gauge rings the water trough",
  "fishing solunar table smells like tackle boxes",
  "harbor swell forecast rocks the login modal",
  "buoy observation blinks from a steel horizon",
  "offshore wind map braids the cables neatly",
  "microclimate note pinned behind the vineyard row",
  "frost pocket layer chills the valley checkbox",
  "rain shadow tooltip stands behind the ridge",
  "weather archive sneezes dust into 1998",
  "climate scenario slider squeaks toward midcentury",
  "resilience scorecard packs batteries and soup",
  "environment portal signs in with a mossy key",
];
